# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestWork',
            new_name='RequestedWork',
        ),
        migrations.RenameField(
            model_name='approvedwork',
            old_name='request_work',
            new_name='requested_work',
        ),
        migrations.RenameField(
            model_name='requestedwork',
            old_name='request_user',
            new_name='requested_user',
        ),
        migrations.AlterField(
            model_name='job',
            name='position_description',
            field=models.TextField(max_length=100),
        ),
    ]
